[window.padding]
x = 6
y = 6

[window]
dynamic_padding = false
opacity = 0.9
title = "Alacritty"

[font]
size = 13.0
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }

[scrolling]
history = 10000
multiplier = 20
